---
- name: Instalar vagrant en servidor
  ##hosts: vagrant
  hosts: all
  become: yes

  
  vars:
    sdkman_dir: "/usr/local/sdkman"
    ansible_user: "vagrant"
    vagrant_repo_url: "https://pkg.vagrant.io/debian-stable"
    vagrant_key_url: "https://pkg.vagrant.io/debian-stable/vagrant.io-2023.key"

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Instalar dependencias
      apt:
        name:
          - zip
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Instalar SDKMAN bajo usuario vagrant
      become: yes
      become_user: vagrant
      shell: |
        curl -s "https://get.sdkman.io" | bash
      args:
        creates: "/home/vagrant/.sdkman/bin/sdkman-init.sh"

    - name: Instalar última versión de Java con SDKMAN
      become: yes
      become_user: vagrant
      shell: |
        source /home/vagrant/.sdkman/bin/sdkman-init.sh && sdk install java
      args:
        executable: /bin/bash

    - name: Obtener la versión de Java instalada
      become: yes
      become_user: vagrant
      shell: |
        source /home/vagrant/.sdkman/bin/sdkman-init.sh && sdk current java | awk '{print $NF}'
      args:
        executable: /bin/bash
      register: java_version

    - name: Establecer esa versión como default
      become: yes
      become_user: vagrant
      ignore_errors: yes
      shell: |
        source /home/vagrant/.sdkman/bin/sdkman-init.sh && sdk default java {{ java_version.stdout }}
      args:
        executable: /bin/bash       

    - name: Agregar clave GPG de vagrant
      apt_key:
        url: "{{ vagrant_key_url }}"
        state: present

    - name: Agregar repositorio de vagrant
      apt_repository:
        repo: "deb {{ vagrant_repo_url }} binary/"
        state: present

    - name: Instalar vagrant
      apt:
        name: vagrant
        state: present
        update_cache: yes

    - name: Asegurar que vagrant esté habilitado y corriendo
      systemd:
        name: vagrant
        state: started
        enabled: yes
